import Head from 'next/head';
import { Provider } from 'reakit';

export default function Home() {
  return (
    <Provider>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </Provider>
  );
}
